version: "3"
services:
  db:
    image: postgres
    container_name: "db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=financial
      - POSTGRES_USER=postgres

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 9999:9999
    depends_on:
     - db
